# Generated by Django 5.1 on 2024-11-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homestay_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_time', models.DateTimeField()),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay_manager.homestay')),
            ],
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_manager.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay_manager.service')),
            ],
        ),
    ]
