# Generated by Django 5.1 on 2024-09-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='rate',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
