# Generated by Django 5.1 on 2024-10-03 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homestay_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='rate',
        ),
        migrations.AlterField(
            model_name='homestay',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homestay',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='homestay',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homestays', to='home.province'),
            preserve_default=False,
        ),
    ]
