# Generated by Django 5.1 on 2024-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_province_remove_homestay_rate_alter_homestay_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homestay',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
