# Generated by Django 5.1 on 2024-10-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homestay_rating_alter_homestay_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homestay',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
