# Generated by Django 5.1 on 2024-10-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_delete_homestay_delete_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homestays', to='home.province')),
            ],
        ),
    ]
