# Generated by Django 5.1 on 2024-10-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
