# Generated by Django 5.1 on 2024-11-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homestay_id_alter_province_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homestay',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
