# Generated by Django 5.1 on 2024-11-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='facilities',
            field=models.ManyToManyField(to='homestay_manager.homestayfacilities'),
        ),
        migrations.DeleteModel(
            name='HomestayFacility',
        ),
    ]
