# Generated by Django 5.1 on 2024-11-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0003_homestay_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='services',
            field=models.ManyToManyField(to='homestay_manager.service'),
        ),
        migrations.DeleteModel(
            name='HomestayService',
        ),
    ]
