# Generated by Django 5.1 on 2024-11-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0004_homestay_services_delete_homestayservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='homestay',
        ),
        migrations.RemoveField(
            model_name='room',
            name='numbers',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Phòng ngủ giường đôi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='HomestayRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay_manager.homestay')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay_manager.room')),
            ],
        ),
        migrations.AddField(
            model_name='homestay',
            name='rooms',
            field=models.ManyToManyField(related_name='homestays', through='homestay_manager.HomestayRoom', to='homestay_manager.room'),
        ),
    ]
