# Generated by Django 5.1 on 2024-11-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0005_remove_room_homestay_remove_room_numbers_room_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
    ]
