<<<<<<< HEAD
# Generated by Django 5.1 on 2024-11-13 16:55
=======
# Generated by Django 5.1 on 2024-11-14 07:32
>>>>>>> 7b8bbf31e06ef567484b567325f169ec577055a3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('homestay_manager', '0006_remove_room_type'),
=======
        ("homestay_manager", "0006_remove_room_type"),
>>>>>>> 7b8bbf31e06ef567484b567325f169ec577055a3
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='homestay',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homestay_images/'),
=======
            model_name="homestay",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="homestay_images/"
            ),
>>>>>>> 7b8bbf31e06ef567484b567325f169ec577055a3
        ),
    ]
