# Generated by Django 5.1 on 2024-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0007_homestay_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestayroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
