# Generated by Django 5.1.3 on 2024-11-17 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0009_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
    ]
