# Generated by Django 5.1.3 on 2024-11-17 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0010_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
