# Generated by Django 5.1 on 2024-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay_manager', '0012_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestayroom',
            name='descriptions',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
